# Generated by Django 5.1.7 on 2025-03-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbs', '0002_rename_product_obj_orderitems_product_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='status',
            new_name='table_status',
        ),
    ]
