# Generated by Django 5.1.7 on 2025-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbs', '0003_rename_status_table_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
